export const ADD_PRODUCT = "ADD_PRODUCT";
export const CHANGE_AMOUNT_PRODUCT = "CHANGE_AMOUNT_PRODUCT";
export const CART_TOTAL = "CART_TOTAL";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const CART_RESET = "CART_RESET";
export const ADD_FORM_VALUES = "ADD_FORM_VALUES";
export const GET_DELIVERY_PAYMENT_VALUES = "GET_DELIVERY_PAYMENT_VALUES";
export const ORDER_TOTAL = "ORDER_TOTAL";
